import { test, expect } from '@playwright/test';

test('create an Order', async ({ page }) => {
  await page.goto('https://ilarionhalushka.github.io/jekyll-ecommerce-demo/');
  await page.getByRole('navigation').getByRole('link', { name: 'Products' }).click();
  await page.getByRole('link', { name: 'Gavin the Tiger' }).click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByLabel('Full name').click();
  await page.getByLabel('Full name').fill('fds');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('fdsfs@fsdfs/fsds');
  await page.locator('.snipcart-textbox').first().click();
  await page.getByLabel('Street address').fill('free');
  await page.getByText('Freedom Drive').click();
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('Charlotte');
  await page.getByLabel('Country').click();
  await page.getByLabel('Country').click();
  await page.getByLabel('Country').fill('United States');
  await page.getByLabel('Apt/Suite').click();
  await page.getByLabel('Apt/Suite').fill('1');
  await page.locator('.snipcart-form__row > div > .snipcart-typeahead > .snipcart-typeahead__content > .snipcart-typeahead__select > .snipcart-typeahead__input > .snipcart-form__select-wrapper > .snipcart-textbox').click();
  await page.getByLabel('Province/State').click();
  await page.locator('#snipcart-billing-form div').filter({ hasText: 'Province/State Alabama Alaska' }).nth(2).click();
  await page.getByLabel('Postal/ZIP code').click();
  await page.getByLabel('Postal/ZIP code').fill('555');
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').fill('fdsfs@fsdfs.fsds');
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').fill('4242 4242 4242 4242');
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').click();
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').fill('12/25');
  await page.frameLocator('iframe').getByPlaceholder('CVV').click();
  await page.frameLocator('iframe').getByPlaceholder('CVV').fill('123');
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.getByRole('heading', { name: 'Thank you for your order' }).click();
  await page.getByRole('button', { name: 'Continue shopping' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Products' }).click();
});